# Generated by Django 5.0.4 on 2024-05-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoSageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
