# Generated by Django 5.0.4 on 2024-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoSageApp', '0003_useraccount_budget_limit_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
