# Generated by Django 5.0.4 on 2024-05-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoSageApp', '0006_useraccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='budget_limit_active',
            field=models.BooleanField(default=False),
        ),
    ]
