# Generated by Django 5.0.4 on 2024-05-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoSageApp', '0007_alter_useraccount_budget_limit_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=999999999.99, max_digits=10),
        ),
    ]
