# Generated by Django 5.0.4 on 2024-05-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoSageApp', '0008_alter_useraccount_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=999999, max_digits=10),
        ),
    ]
